FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build the React app for production
RUN npm run build

# Install a simple static server
RUN npm install -g serve

EXPOSE 3000

# Serve the 'build' directory on port 3000
CMD ["serve", "-s", "build", "-l", "3000"]
